### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ZQSong1997** [fqyuu/CatDM#1]
Hello, I found that there is no NYC_FILTER_POI.txt file when I run the code, which resulted in an error report. How is this data generated and can you publish it? Thank you very much！

**Comment by fqyuu** [comment]
Thank you!  We have submitted the updated project.

**Comment by ZQSong1997** [comment]
Thank you！

**Comment by ZQSong1997** [comment]
Hello，我重新运行了您的代码，还是没有解决问题。第一个就是前面提到的：data文件夹里没有NYC_FILTER_POI.txt这个文件，代码因此不能正常运行。第二个我比较疑惑，您的代码有调用GPU吗？怎么代码中写的是tf.device("/cpu:0")。
希望能得到您的解答，谢谢！

**Comment by fqyuu** [comment]
你好，我这边运行没问题，请确定你重新download整个project。如果确实还报错，可以在运行train.py之前尝试手动或在直接程序中编写相关语句新建一个空的NYC_FILTER_POI.txt文件，这文件是某模块生成文件，某些模块可能在生成之前进行了读取。另外，tensoflow的GPU调用需要自行配置环境后修改device的调用。

**Comment by fqyuu** [comment]
你好，我这边运行没问题，请确定你重新download整个project。如果确实还报错，可以在运行train.py之前尝试手动或在直接程序中编写相关语句新建一个空的NYC_FILTER_POI.txt文件，这文件是某模块生成文件，可能其他模块在其生成之前进行了读取操作。另外，此版本可直接运行在cpu上，tensorflow的GPU调用需要自行配置环境后修改device的调用。
